### ISSUE TITLE
A whole new spin on the icon "problem"

### ISSUE THREAD

**Issue by Just-another-pleb** [DeanCording/node-red-contrib-fan#3]
I accept it is tricky getting everyone happy.

On a side note to anyone reading on how to make the icon smaller:
When editing the node, click the APPEARANCE button (the right most one) and then click/select the "label hide" switch.
This will make the icon a 1x1 size.

But on this issue:
I know that this node is mostly aimed at simply tidying up messy _wires_.
But I am finding it increasingly handy to segment flows.

It may be nice if the background was grey like the LINK node, and a name is possible.
This way when you use this node - as it was meant to be - at an input of a "routine" you can name that routine in the node, rather than adding a description node.

Just a thought.

But believe me:  I love the node and use it a lot.
And discovering the way to shrink the icon!   Wow!

**Comment by StephanStS** [comment]
@DeanCording, @Just-another-pleb: My proposal would be to change the node's color from #165b2f to #7C9A8C. This gives a better contrast to the node name in black letters.
Also to give the node a name seems to be a bit nicer: return this.name||"fan".

The fan.html upper part would then be: 
```
<script type="text/javascript">  
    RED.nodes.registerType('fan',{  
        category: 'function', 
        color: '#7C9A8C', 
        defaults: { 
                    }, 
        inputs:1, 
        outputs:1, 
        icon: "font-awesome/fa-minus", 
        label: function() { 
            return this.name||"fan"; 
        } 
    }); 
</script>
```
Result: See https://raw.githubusercontent.com/StephanStS/node-red-contrib-fan/master/fan-node.png.

If this would be an option I would make a pull request and additionally do some new screenshots for the README.md file.

**Comment by StephanStS** [comment]
@Just-another-pleb: Is the actual committed version ([see there](https://github.com/DeanCording/node-red-contrib-fan)) what you can live with?
If yes, you could close this issue.

**Comment by Just-another-pleb** [comment]
Sorry for the long delay in my reply.

That looks really good.

Thanks.

Installed and looking great!

**Comment by StephanStS** [comment]
@Just-another-pleb, @DeanCording: Could someone of you please close this issue?

**Comment by Just-another-pleb** [comment]
What you did is fantastic.

I am happy with the look.

**Comment by Just-another-pleb** [comment]
(Sorry.  I just got back from a week away and my head isn't/hadn't caught
up.   Closed now.)
