### ISSUE TITLE
Version 1.0.2 has to be released to npm

### ISSUE THREAD

**Issue by StephanStS** [DeanCording/node-red-contrib-fan#5]
What need to be done to finish the version 1.0.2 release?

- Label the release as version 1.0.2 within the [github releases page](https://github.com/DeanCording/node-red-contrib-fan/releases)
- Publish version 1.0.2 to [npm](https://www.npmjs.com/package/node-red-contrib-fan)
- Request refresh on the [node-red flow page
](https://flows.nodered.org/node/node-red-contrib-fan)
- Close this issue

**Comment by DeanCording** [comment]
Done
